const mongoose = require('mongoose');

const orderSchema = new mongoose.Schema({
  order_id: { 
    type: mongoose.Schema.Types.ObjectId, 
    auto: true // Optional: auto-generated by MongoDB
  },


  user_id: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User',
    required: true 
  },

  total_price: { 
    type: Number, 
    required: true 
  }

}, {
  timestamps: true
});

const Order = mongoose.model('Order', orderSchema);

module.exports = Order;
